### ISSUE TITLE
Save and Load

### ISSUE THREAD

**Issue by blakehartley** [roostalol/RNGHelper#35]
It would be nice if it were possible to save the current state of all of the next boxes in the program to a file, and load that state from the file that was created. Thus, if had already filled out something like:

![ff12rnghelper_2017-08-10_18-01-53](https://user-images.githubusercontent.com/30282035/29194149-54837c6c-7df6-11e7-9add-5139b3ee67ba.png)

I would want to hit "save," creating a file which I could load to reproduce this state. The position of the RNG does not need to be saved, nor does the last cure value... but everything else would be nice.

**Comment by erickt420** [comment]
Based on discord discussion:
* Basic File Picker will probably suffice.
* Must be able to be used w/ one hand.

**Comment by Hoishin** [comment]
it'd be nice if you can make the save file editable through text editor like JSON, so you can make profiles easily
