### ISSUE TITLE
Issue with Capturing

### ISSUE THREAD

**Issue by zer0skar** [roostalol/RNGHelper#39]
If I want to capture the RNG Helper during my stream and want to go back and forth between Rare Game and Chests, it won't work since it creates a new window. It's a minor thing and has nothing to do with the program working properly - just a little thing that would be cool

**Comment by Hoishin** [comment]
Using different options for OBS Studio Window Capture does not fix.

**Comment by erickt420** [comment]
Okay, so instead of opening and closing the forms, you want 1 form that changes between the different pages? Would this solve the problem?

**Comment by zer0skar** [comment]
Probably

**Comment by erickt420** [comment]
Fixed by release V3.2.

Fixed by commit #43.
